#+TITLE: Newsletter Ideas

* Newsletter Ideas
** Wi Xing

#+BEGIN_SRC dot :file dot_success.png
  digraph {
  metal -> water
  water -> wood
  wood -> fire
     fire -> earth
  earth -> metal
  dot -> "Success" [style=dotted]
  }
#+END_SRC

#+CAPTION: We love graphs!
#+LABEL: fig.dot
#+RESULTS:
file:dot_success.png]]

This is the [[fig.dot][graph]].


(defun wu ()
  (with-graph (:nodes (element)
               :edges ((generates) (overcomes))
               :graph ((metal water wood fire earth metal)
                       (overcomes metal wood earth water fire metal)))
    (print)))


** TODO add target='_blank' to html exports
** Unix Shell tech tip

   Everyone has their favorite shell aliases. Here are a few of our favorites:

 #+BEGIN_EXAMPLE
 alias a=alias
 alias c=clear
 alias e='emacs -nw'
 alias m=make
 alias pg=less
 alias the="dict -d moby-thesaurus"

 #+END_EXAMPLE
* Crossing the Collosum

  “Hacker slang also challenges some common linguistic and
  anthropological assumptions. For example, in the early 1990s it became
  fashionable to speak of ‘low-context’ versus ‘high-context’
  communication, and to classify cultures by the preferred context level
  of their languages and art forms. It is usually claimed that
  low-context communication (characterized by precision, clarity, and
  completeness of self-contained utterances) is typical in cultures
  which value logic, objectivity, individualism, and competition; by
  contrast, high-context communication (elliptical, emotive,
  nuance-filled, multi-modal, heavily coded) is associated with cultures
  which value subjectivity, consensus, cooperation, and tradition. What
  then are we to make of hackerdom, which is themed around extremely
  low-context interaction with computers and exhibits primarily
  “low-context” values, but cultivates an almost absurdly high-context
  slang style?” - [[http://www.catb.org/jargon/html/introduction.html][The Jargon File]]
* Perl RSA
  http://www.cypherspace.org/rsa/story2.html

#+BEGIN_SRC perl :results output :var k=10001
print pack"C*",split/\D+/,`echo "16iII*o\U@{$/=$z;[(pop,pop,unpack"H*",<>)]}\EsMsKsN0[lN*1lK[d2%Sa2/d0<X+d*lMLa^*lN%0]dsXx++lMlN/dsM0<J]dsJxp"|dc`
#+END_SRC

#+RESULTS:

